package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private long accountId;
	private Long userId;
	private double amount;
	private Integer curr;
	private Date dateInput;
	private String description;
	private boolean complete;
	private boolean active;
	private Long currencyId;
	private Long treeId;

	public Account() {
	}

	public Account(long accountId, double amount, Date dateInput,
			boolean complete, boolean active) {
		this.accountId = accountId;
		this.amount = amount;
		this.dateInput = dateInput;
		this.complete = complete;
		this.active = active;
	}

	public Account(long accountId, Long userId, double amount, Integer curr,
			Date dateInput, String description, boolean complete,
			boolean active, Long currencyId, Long treeId) {
		this.accountId = accountId;
		this.userId = userId;
		this.amount = amount;
		this.curr = curr;
		this.dateInput = dateInput;
		this.description = description;
		this.complete = complete;
		this.active = active;
		this.currencyId = currencyId;
		this.treeId = treeId;
	}

	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Integer getCurr() {
		return this.curr;
	}

	public void setCurr(Integer curr) {
		this.curr = curr;
	}

	public Date getDateInput() {
		return this.dateInput;
	}

	public void setDateInput(Date dateInput) {
		this.dateInput = dateInput;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isComplete() {
		return this.complete;
	}

	public void setComplete(boolean complete) {
		this.complete = complete;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Long getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Long currencyId) {
		this.currencyId = currencyId;
	}

	public Long getTreeId() {
		return this.treeId;
	}

	public void setTreeId(Long treeId) {
		this.treeId = treeId;
	}

}
