package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private CityId id;

	public City() {
	}

	public City(CityId id) {
		this.id = id;
	}

	public CityId getId() {
		return this.id;
	}

	public void setId(CityId id) {
		this.id = id;
	}

}
