package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * Creteria6 generated by hbm2java
 */
public class Creteria6 implements java.io.Serializable {

	private long creteria6Id;
	private String name;
	private Boolean active;
	private Long langId;
	private long linkId;
	private long catalogId;
	private String label;

	public Creteria6() {
	}

	public Creteria6(long creteria6Id, long linkId, long catalogId) {
		this.creteria6Id = creteria6Id;
		this.linkId = linkId;
		this.catalogId = catalogId;
	}

	public Creteria6(long creteria6Id, String name, Boolean active,
			Long langId, long linkId, long catalogId, String label) {
		this.creteria6Id = creteria6Id;
		this.name = name;
		this.active = active;
		this.langId = langId;
		this.linkId = linkId;
		this.catalogId = catalogId;
		this.label = label;
	}

	public long getCreteria6Id() {
		return this.creteria6Id;
	}

	public void setCreteria6Id(long creteria6Id) {
		this.creteria6Id = creteria6Id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Long getLangId() {
		return this.langId;
	}

	public void setLangId(Long langId) {
		this.langId = langId;
	}

	public long getLinkId() {
		return this.linkId;
	}

	public void setLinkId(long linkId) {
		this.linkId = linkId;
	}

	public long getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(long catalogId) {
		this.catalogId = catalogId;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
