package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	private long imageId;
	private String imgname;
	private String imgUrl;
	private Long userId;

	public Images() {
	}

	public Images(long imageId) {
		this.imageId = imageId;
	}

	public Images(long imageId, String imgname, String imgUrl, Long userId) {
		this.imageId = imageId;
		this.imgname = imgname;
		this.imgUrl = imgUrl;
		this.userId = userId;
	}

	public long getImageId() {
		return this.imageId;
	}

	public void setImageId(long imageId) {
		this.imageId = imageId;
	}

	public String getImgname() {
		return this.imgname;
	}

	public void setImgname(String imgname) {
		this.imgname = imgname;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

}
