package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * PayGateway generated by hbm2java
 */
public class PayGateway implements java.io.Serializable {

	private PayGatewayId id;

	public PayGateway() {
	}

	public PayGateway(PayGatewayId id) {
		this.id = id;
	}

	public PayGatewayId getId() {
		return this.id;
	}

	public void setId(PayGatewayId id) {
		this.id = id;
	}

}
