package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * ServiceStatusEventsHistory generated by hbm2java
 */
public class ServiceStatusEventsHistory implements java.io.Serializable {

	private ServiceStatusEventsHistoryId id;

	public ServiceStatusEventsHistory() {
	}

	public ServiceStatusEventsHistory(ServiceStatusEventsHistoryId id) {
		this.id = id;
	}

	public ServiceStatusEventsHistoryId getId() {
		return this.id;
	}

	public void setId(ServiceStatusEventsHistoryId id) {
		this.id = id;
	}

}
