package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * Site generated by hbm2java
 */
public class Site implements java.io.Serializable {

	private long siteId;
	private String host;
	private Long owner;
	private boolean active;
	private String homeDir;
	private String siteDir;
	private String person;
	private String phone;
	private String address;
	private String subjectSite;
	private String nickSite;
	private String companyName;

	public Site() {
	}

	public Site(long siteId, boolean active) {
		this.siteId = siteId;
		this.active = active;
	}

	public Site(long siteId, String host, Long owner, boolean active,
			String homeDir, String siteDir, String person, String phone,
			String address, String subjectSite, String nickSite,
			String companyName) {
		this.siteId = siteId;
		this.host = host;
		this.owner = owner;
		this.active = active;
		this.homeDir = homeDir;
		this.siteDir = siteDir;
		this.person = person;
		this.phone = phone;
		this.address = address;
		this.subjectSite = subjectSite;
		this.nickSite = nickSite;
		this.companyName = companyName;
	}

	public long getSiteId() {
		return this.siteId;
	}

	public void setSiteId(long siteId) {
		this.siteId = siteId;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public Long getOwner() {
		return this.owner;
	}

	public void setOwner(Long owner) {
		this.owner = owner;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getHomeDir() {
		return this.homeDir;
	}

	public void setHomeDir(String homeDir) {
		this.homeDir = homeDir;
	}

	public String getSiteDir() {
		return this.siteDir;
	}

	public void setSiteDir(String siteDir) {
		this.siteDir = siteDir;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSubjectSite() {
		return this.subjectSite;
	}

	public void setSubjectSite(String subjectSite) {
		this.subjectSite = subjectSite;
	}

	public String getNickSite() {
		return this.nickSite;
	}

	public void setNickSite(String nickSite) {
		this.nickSite = nickSite;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

}
