package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * StoreSession generated by hbm2java
 */
public class StoreSession implements java.io.Serializable {

	private StoreSessionId id;

	public StoreSession() {
	}

	public StoreSession(StoreSessionId id) {
		this.id = id;
	}

	public StoreSessionId getId() {
		return this.id;
	}

	public void setId(StoreSessionId id) {
		this.id = id;
	}

}
