package com.cbsinc.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

/**
 * XslSubj generated by hbm2java
 */
public class XslSubj implements java.io.Serializable {

	private long xslSubjId;
	private String name;
	private String description;
	private boolean active;

	public XslSubj() {
	}

	public XslSubj(long xslSubjId, boolean active) {
		this.xslSubjId = xslSubjId;
		this.active = active;
	}

	public XslSubj(long xslSubjId, String name, String description,
			boolean active) {
		this.xslSubjId = xslSubjId;
		this.name = name;
		this.description = description;
		this.active = active;
	}

	public long getXslSubjId() {
		return this.xslSubjId;
	}

	public void setXslSubjId(long xslSubjId) {
		this.xslSubjId = xslSubjId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
