services:

  cms2servicediscovery:
    image: cmsmanhattan/cms2servicediscovery:1.0.10
    ports:
      - 876:8761
    restart: always
    networks:
      network:
        ipv4_address: 10.5.0.7  
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    # image: cmsmanhattan/cmsone:last
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    networks:
      network:
        ipv4_address: 10.5.0.5  
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=grabfix
      - MYSQL_DATABASE=cmsdb
      - MYSQL_USER=cms
      - MYSQL_PASSWORD=grabfix
    expose:
      - 3306
      - 33060

#  db:
#    image: msql:8.0
#    #image: msql:5.7
#    command: --init-file /data/application/nit.sql
#    volumes:
#        - ./init.sql:/data/application/nit.sql
#        #- ./docker/images/sql-scripts:/docker-entrypoint-nitdb.d
#    networks:
#      network:
#        ipv4_address: 10.5.0.5    
#    restart: always
#    environment:
#        MYSQL_ROOT_USER: root
#        MYSQL_ROOT_PASSWORD: grabfix
#        MYSQL_DATABASE: cmsdb
#        MYSQL_USER: root
#        MYSQL_PASSWORD: grabfix
#    expose:
#      - 3306
#      - 33060

      
  cmsmanhattan:
    image: cmsmanhattan/cmsone:0.0.10
    ports:
      - 80:8080
    restart: always
    environment:
      - CMS_DB_JDBC_URL=jdbc:mysql://10.5.0.5:3306/cmsdb
      - CMS_DB_USER=root
      - CMS_DB_PASSWORD=grabfix
      - CMS_DB_USE_SSL=false
      - CMS_DB_AUTO_RECONECT=false
    networks:
      network:
        ipv4_address: 10.5.0.4  
        
 ## mail server ##       
  james:
#    depends_on:
#      - mariadb
    image: apache/james:jpa-latest
    container_name: james
    ports:
      - 25:25
      - 110:110
      - 143:143
      - 465:465
      - 993:993
      - 119:119
      - 587:587
      - 8000:8000        
      - 4555:4555
      - 9999:9999       
    hostname: 10.5.0.3
    command:
      - --generate-keystore
#    volumes:
#      - $PWD/mariadb-java-client-2.7.2.jar:/root/libs/mariadb-java-client-2.7.2.jar
#      - $PWD/sample-configuration/james-database-mariadb.properties:/root/conf/james-database.properties
#      - $PWD/keystore:/root/conf/keystore
    networks:
      network:
        ipv4_address: 10.5.0.3       


  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    #command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data 
    networks:
      network:
        ipv4_address: 10.5.0.17   

volumes:
  db_data:
  cache:
    driver: local
  
  
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1  