services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=grabfix
      - MYSQL_DATABASE=cmsdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=grabfix
    expose:
      - 3306
      - 33060
  wordpress:
    image: cmsmanhattan/cmsone:latest
    ports:
      - 80:80
    restart: always
    environment:
      - CMS_DB_JDBC_URL=jdbc:mysql://10.0.0.17:3306/cmsdb
      - CMS_DB_USER=root
      - CMS_DB_PASSWORD=grabfix
      - CMS_DB_USE_SSL=false
      - CMS_DB_AUTO_RECONECT=false

volumes:
  db_data: