version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    networks:
      network:
        ipv4_address: 10.5.0.5    
    restart: always
    environment:
      - MYSQL_DATABASE=cmsdb
      - MYSQL_ROOT_PASSWORD=grabfix
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cmsmanhattan:
    image: cmsmanhattan/cmsone:0.0.8
    ports:
      - 80:8080
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: 10.5.0.5
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: grabfix
      DB_NAME: cmsdb
    networks:
      network:
        ipv4_address: 10.5.0.4   
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local
    
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1  